apiVersion: v1
kind: Service
metadata:
  name: dockerprac
spec:
  selector:
    app: dockerprac
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 32000
